### ISSUE TITLE
Explain timing and consider self-discharge current

### ISSUE THREAD

**Issue by gnbl** [strange-v/supercap#1]
Thanks for the calculator!
Could you spare some time to add an explanation for the different modes - are they averaged (make them configurable)? 
For instance, if I set Sleep to 1 sec @ 1 µA and the others to zero, I get a result like "7y 2777d 18h 40m"...
Also, it would be nice to allow for a constant current to approximate the self-discharge (there may be a better approach).

**Comment by strange-v** [comment]
Hi @gnbl ,

Correct, the average consumption is used to calculate the discharge duration:
`result = (runCurrent * runTime + idleCurrent * idleTime + sleepCurrent * sleepTime) / (runTime + idleTime + sleepTime)`

This calculator was created for relatively small supercapacitors, where self-discharging is not highly important. I thought about adding it as a parameter, but:
- it's often missed in the datasheets (at least for the capacitors I used);
- it's quite non-linear and usually represented by a chart;

Regarding different modes. In my project (a radio thermometer), the modes can be described like this:
- Sleep - the MCU and all sensors are in deep sleep mode (~60sec)
- Idle - the MCU and sensors are waked up and perform measurements (~50ms)
- Run - transmission of the data (~4ms)

I agree that configurable modes would be a great solution, but, unfortunately, I have no plans of adding them shortly.

**Comment by gnbl** [comment]
Thanks for taking the time to respond!
